/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.33. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"

	syncagentv1alpha1 "github.com/kcp-dev/api-syncagent/sdk/apis/syncagent/v1alpha1"
)

// RelatedResourceWatchApplyConfiguration represents a declarative configuration of the RelatedResourceWatch type for use
// with apply.
type RelatedResourceWatchApplyConfiguration struct {
	ByOwner    *syncagentv1alpha1.RelatedResourceWatchByOwner `json:"byOwner,omitempty"`
	BySelector *v1.LabelSelectorApplyConfiguration            `json:"bySelector,omitempty"`
}

// RelatedResourceWatchApplyConfiguration constructs a declarative configuration of the RelatedResourceWatch type for use with
// apply.
func RelatedResourceWatch() *RelatedResourceWatchApplyConfiguration {
	return &RelatedResourceWatchApplyConfiguration{}
}

// WithByOwner sets the ByOwner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ByOwner field is set to the value of the last call.
func (b *RelatedResourceWatchApplyConfiguration) WithByOwner(value syncagentv1alpha1.RelatedResourceWatchByOwner) *RelatedResourceWatchApplyConfiguration {
	b.ByOwner = &value
	return b
}

// WithBySelector sets the BySelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BySelector field is set to the value of the last call.
func (b *RelatedResourceWatchApplyConfiguration) WithBySelector(value *v1.LabelSelectorApplyConfiguration) *RelatedResourceWatchApplyConfiguration {
	b.BySelector = value
	return b
}
