/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen-v0.33. DO NOT EDIT.

package v1alpha1

// RelatedResourceWatchApplyConfiguration represents a declarative configuration of the RelatedResourceWatch type for use
// with apply.
type RelatedResourceWatchApplyConfiguration struct {
	ByOwner *RelatedResourceWatchByOwnerApplyConfiguration `json:"byOwner,omitempty"`
	ByLabel map[string]string                              `json:"byLabel,omitempty"`
}

// RelatedResourceWatchApplyConfiguration constructs a declarative configuration of the RelatedResourceWatch type for use with
// apply.
func RelatedResourceWatch() *RelatedResourceWatchApplyConfiguration {
	return &RelatedResourceWatchApplyConfiguration{}
}

// WithByOwner sets the ByOwner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ByOwner field is set to the value of the last call.
func (b *RelatedResourceWatchApplyConfiguration) WithByOwner(value *RelatedResourceWatchByOwnerApplyConfiguration) *RelatedResourceWatchApplyConfiguration {
	b.ByOwner = value
	return b
}

// WithByLabel puts the entries into the ByLabel field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ByLabel field,
// overwriting an existing map entries in ByLabel field with the same key.
func (b *RelatedResourceWatchApplyConfiguration) WithByLabel(entries map[string]string) *RelatedResourceWatchApplyConfiguration {
	if b.ByLabel == nil && len(entries) > 0 {
		b.ByLabel = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ByLabel[k] = v
	}
	return b
}
