# Copyright 2025 The KCP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

presubmits:
  - name: pull-api-syncagent-verify
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.24.9-1
          command:
            - hack/ci/verify.sh
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-api-syncagent-lint
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.24.9-1
          command:
            - make
            - lint
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-api-syncagent-build-image
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/containers/buildah:v1.38.0
          command:
            - hack/ci/build-image.sh
          env:
            - name: DRY_RUN
              value: "1"
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 1Gi
              cpu: 1

  - name: pull-api-syncagent-test
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.24.9-1
          command:
            - make
            - test
          env:
            - name: USE_GOTESTSUM
              value: "1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-api-syncagent-test-e2e-kcp-0.27
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.24.9-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_VERSION
              value: "0.27.1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2

  - name: pull-api-syncagent-test-e2e-kcp-0.28
    always_run: true
    decorate: true
    clone_uri: "https://github.com/kcp-dev/api-syncagent"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: ghcr.io/kcp-dev/infra/build:1.24.9-1
          command:
            - hack/ci/run-e2e-tests.sh
          env:
            - name: KCP_VERSION
              value: "0.28.1"
          resources:
            requests:
              memory: 4Gi
              cpu: 2
